# NOTE: Change the pre-release to the release manually!
name: Pre-release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - run: deno task build
      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
        with:
          subject-path: |
            dist/main.js
            dist/manifest.json
            dist/styles.css
      - run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --prerelease \
            --generate-notes \
            ./dist/main.js ./dist/manifest.json ./dist/styles.css
        env:
          GITHUB_TOKEN: ${{ github.token }}
